name: EMO
description: Rebuild project with multi-flatform mobile, web app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.12+20231228

environment:
  sdk: '>=3.1.1 <4.0.0'

isar_version: &isar_version ^3.1.0+1 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Adaptive Scrollbar is a library that allows you to create one or more desktop-style scrollbars on a single
  # screen, each of which is bound only to its own object and placed in its own place on the screen.
  adaptive_scrollbar: ^2.1.2
  cupertino_icons: ^1.0.6
  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.3.0
  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData,
  # Request Cancellation, File downloading, Timeout etc.
  dio: ^5.4.0
  retrofit: ^4.0.3
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  # A clean and lightweight loading/toast widget for Flutter, Easy to use without context,
  # Support iOSã€Android and Web
  flutter_easyloading: ^3.0.5
  # A CacheManager to download and cache files in the cache directory of the app.
  # Various settings on how long to keep a file can be changed.
  flutter_cache_manager: ^3.3.0
  # A powerful Flutter chart library, currently supporting Line Chart, Bar Chart and Pie Chart.
  fl_chart: ^0.65.0
  get: ^4.6.6
  get_it: ^7.6.4
  go_router: ^12.1.3
  html: ^0.15.4
  hive: ^2.2.3
  hive_flutter: 1.1.0
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  share: ^2.0.4
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^23.2.7
  syncfusion_flutter_datepicker: ^23.2.7
  uni_links: ^0.5.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  uuid: any
  #  form
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  logger: any
  #  international
  intl: any
  intl_utils: ^2.8.4
  #  list, map, set method
  collection: any
  rxdart: any
  flutter_typeahead: ^4.7.0
  scrollable_positioned_list: ^0.3.8
  equatable: ^2.0.5
  pull_to_refresh: ^2.0.0
  open_file:
    git:
      url: https://github.com/crazecoder/open_file
  # select file
  file_picker: ^6.1.1
  universal_html: ^2.2.4
  mask_text_input_formatter: ^2.4.0
  webview_flutter: ^3.0.4
  mobile_scanner: ^2.1.0
  kt_dart: any
  qr_flutter: ^4.0.0
  marquee: ^2.2.3
  math_expressions: ^2.3.1
  dart_ipify: ^1.1.1
  image_picker: ^0.8.6
  timezone: ^0.9.1
  flutter_inappwebview: 5.7.2+3
  flutter_dash: 1.0.0
  empty_widget: 0.0.5
  awesome_dialog: 3.0.2
  device_info_plus: ^9.1.1
  shimmer: ^2.0.0
  font_awesome_flutter: ^10.1.0
  connectivity_plus: "3.0.2"
  animated_bottom_navigation_bar: ^1.2.0
  badges: ^2.0.3
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  flutter_flavor: ^3.1.3
  flutter_flavorizr: ^2.1.5
  firebase_crashlytics: ^3.4.8
  platform_device_id: ^1.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.11.0
  mocktail: ^1.0.1
  build_runner: any
  flutter_lints: any
  json_serializable: any
  hive_generator: any
  retrofit_generator: ^8.0.5
  isar_generator: *isar_version


flutter_icons:
    android: false
    ios: true
    remove_alpha_ios: true
    image_path: "assets/logo/logo.png"

flutter_launcher_name:
  name: "EMO"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/GoogleSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/GoogleSans-Light.ttf
          weight: 300
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans-Black.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-Black.ttf
          weight: 800
        - asset: assets/fonts/GoogleSans-Black.ttf
          weight: 900
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons/CustomIcons.ttf
flutter_intl:
  enabled: true
  arb_dir: lib/common/l10n
  output_dir: lib/common/generated
